apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: c1gzc30cm-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap-test-organization-jk/rhtap-qe:35809af85f644e48f42caa5c5cda4d5feb1b3089@sha256:0e63d0cf81e7e226b9429a1bc9fb997266becb9038c49da2adc4e7db649c1af4
          name: container-image
