apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: c1gzc30cm-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: c1gzc30cm-go 
  name: c1gzc30cm-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: c1gzc30cm-go 
